# Copyright 2026 QuerySolo contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate illustrative website scenarios with the real gauge model, without I/O.

The plans, table statistics and laptop below are deliberately synthetic. These are
model outputs, not EXPLAIN captures, actual query timings or hardware measurements.
Run with --write to refresh the TypeScript constants; otherwise verify freshness.
"""
from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "core"))
from querysolo.gauge.model import Thresholds, estimate_plan  # noqa: E402

MACHINE = {"ram": 16_000_000_000, "memory_limit": 12_000_000_000,
           "threads": 8, "free_disk": 100_000_000_000}
DISK_MBPS = 1500
S3_MBPS = 100


def node(name, rows, *children):
    return {"name": name, "extra_info": {"Estimated Cardinality": str(rows)},
            "children": list(children)}


def scenario_inputs(question, storage):
    orders = node("ICEBERG_SCAN", 80_000_000)
    if question == "summary":
        plan = [node("HASH_GROUP_BY", 6, orders)]
        scans = [(80_000_000, 1_200_000_000, 96)]
    elif question == "join":
        customers = node("ICEBERG_SCAN", 5_000_000)
        plan = [node("HASH_JOIN", 80_000_000, orders, customers)]
        scans = [(80_000_000, 2_400_000_000, 96), (5_000_000, 800_000_000, 8)]
    elif question == "sort":
        plan = [node("ORDER_BY", 80_000_000, orders)]
        scans = [(80_000_000, 24_000_000_000, 96)]
    else:
        raise ValueError(question)
    return plan, [{"rows": rows, "bytes": size, "files": files,
                   "bytes_per_row": size / rows,
                   "locality": "remote" if storage == "s3" else "local"}
                  for rows, size, files in scans]


def scenarios():
    result = {}
    keys = ("verdict", "bytes_scanned", "peak_memory", "wall_local",
            "io_seconds", "cpu_seconds", "spill_bytes")
    for question in ("summary", "join", "sort"):
        result[question] = {}
        for storage in ("local", "s3"):
            plan, scans = scenario_inputs(question, storage)
            estimate = estimate_plan(plan, scans, MACHINE, DISK_MBPS,
                                     S3_MBPS if storage == "s3" else None, Thresholds())
            result[question][storage] = {key: estimate[key] for key in keys}
    return result


def render():
    profile = {"ramGb": 16, "queryMemoryGb": 12, "threads": 8, "freeDiskGb": 100,
               "diskMBps": DISK_MBPS, "s3Mbps": S3_MBPS}
    return ("// Copyright 2026 QuerySolo contributors\n"
            "// SPDX-License-Identifier: Apache-2.0\n"
            "// Generated by web/scripts/generate_lookahead.py. Illustrative inputs, not benchmarks.\n"
            f"export const profile = {json.dumps(profile, indent=2)} as const;\n"
            f"export const estimates = {json.dumps(scenarios(), indent=2)} as const;\n")


if __name__ == "__main__":
    target = ROOT / "web/src/data/lookahead-estimates.ts"
    expected = render()
    if "--write" in sys.argv:
        target.write_text(expected)
        print(f"Generated six illustrative gauge estimates: {target}")
    elif not target.exists() or target.read_text() != expected:
        raise SystemExit("Stale Lookahead scenarios: run scripts/generate_lookahead.py --write")
    else:
        print("All six scenarios match the core gauge model.")
