// Copyright 2026 QuerySolo contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by web/scripts/generate_lookahead.py. Illustrative inputs, not benchmarks.
export const profile = {
  "ramGb": 16,
  "queryMemoryGb": 12,
  "threads": 8,
  "freeDiskGb": 100,
  "diskMBps": 1500,
  "s3Mbps": 100
} as const;
export const estimates = {
  "summary": {
    "local": {
      "verdict": "green",
      "bytes_scanned": 1200000000,
      "peak_memory": 134218065,
      "wall_local": 0.81,
      "io_seconds": 0.8,
      "cpu_seconds": 0.4000000000000001,
      "spill_bytes": 0
    },
    "s3": {
      "verdict": "yellow",
      "bytes_scanned": 1200000000,
      "peak_memory": 134218065,
      "wall_local": 96.01,
      "io_seconds": 96.0,
      "cpu_seconds": 0.4000000000000001,
      "spill_bytes": 0
    }
  },
  "join": {
    "local": {
      "verdict": "green",
      "bytes_scanned": 3200000000,
      "peak_memory": 3134217728,
      "wall_local": 2.143333333333333,
      "io_seconds": 2.1333333333333333,
      "cpu_seconds": 0.3580357142857143,
      "spill_bytes": 0
    },
    "s3": {
      "verdict": "yellow",
      "bytes_scanned": 3200000000,
      "peak_memory": 3134217728,
      "wall_local": 256.01,
      "io_seconds": 256.0,
      "cpu_seconds": 0.3580357142857143,
      "spill_bytes": 0
    }
  },
  "sort": {
    "local": {
      "verdict": "yellow",
      "bytes_scanned": 24000000000,
      "peak_memory": 60134217728,
      "wall_local": 80.18895697066667,
      "io_seconds": 16.0,
      "cpu_seconds": 0.5428571428571429,
      "spill_bytes": 48134217728
    },
    "s3": {
      "verdict": "red",
      "bytes_scanned": 24000000000,
      "peak_memory": 60134217728,
      "wall_local": 1984.1889569706666,
      "io_seconds": 1920.0,
      "cpu_seconds": 0.5428571428571429,
      "spill_bytes": 48134217728
    }
  }
} as const;
